/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v0/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contract versions, fact statistics, platform, model counts */
        get: operations["status_api_v0_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nodes, edges, issues and pinned positions of one level */
        get: operations["view_api_v0_view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Component tree with symbol counts and issues */
        get: operations["components_api_v0_components_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/components/{component_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Component model, computed issues, interface symbols, incoming and outgoing edges */
        get: operations["component_api_v0_components__component_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/symbols/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Symbols by name */
        get: operations["search_api_v0_symbols_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A symbol, its definition, component and editor link */
        get: operations["symbol_api_v0_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/symbols/callers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who calls the symbol */
        get: operations["callers_api_v0_symbols_callers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/symbols/callees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the symbol calls */
        get: operations["callees_api_v0_symbols_callees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shortest call chains between two symbols */
        get: operations["paths_api_v0_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/edges/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The refs an edge of a level is made of */
        get: operations["samples_api_v0_edges_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/layout/{scope}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save the pinned positions of one level */
        put: operations["layout_api_v0_layout__scope__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-sent events: facts_changed, model_changed, highlight_changed, reindex_progress */
        get: operations["events_api_v0_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CallEdge */
        CallEdge: {
            /** Caller */
            caller: string;
            /** Callee */
            callee: string;
            /** Caller Name */
            caller_name: string;
            /** Callee Name */
            callee_name: string;
            /** Path */
            path: string;
            /**
             * Line
             * @description 1-based line of the first call
             */
            line: number;
            /** Depth */
            depth: number;
        };
        /** CallList */
        CallList: {
            /** Items */
            items: components["schemas"]["CallEdge"][];
            /** More */
            more: boolean;
        };
        /** ComponentCard */
        ComponentCard: {
            /** Id */
            id: string;
            /** Parent */
            parent: string;
            /** Children */
            children: string[];
            /**
             * Model
             * @description the component file (contract 3) as JSON
             */
            model: {
                [key: string]: unknown;
            };
            /** Symbols */
            symbols: number;
            /** Own Symbols */
            own_symbols: number;
            /** Issues */
            issues: components["schemas"]["Issue"][];
            /**
             * Interface
             * @description provides and explicit symbols, else public header symbols
             */
            interface: components["schemas"]["InterfaceSymbol"][];
            /**
             * Fingerprint
             * @description current interface fingerprint, as sync.fingerprint stores it
             */
            fingerprint: string;
            /** Edges Out */
            edges_out: components["schemas"]["DependencyEdge"][];
            /** Edges In */
            edges_in: components["schemas"]["DependencyEdge"][];
        };
        /** ComponentTree */
        ComponentTree: {
            /** Parent */
            parent: string;
            /** Components */
            components: components["schemas"]["TreeNode"][];
            /**
             * Unassigned
             * @description symbols in no component, shown as the _unassigned node at the top level
             */
            unassigned: number;
        };
        /** Contracts */
        Contracts: {
            /** Api */
            api: string;
            /**
             * Facts
             * @description facts_version of the loaded fact stream
             */
            facts: string | null;
            /** Store */
            store: string;
            /** Model */
            model: string;
            /** Config */
            config: string;
            /** Layout */
            layout: string;
        };
        /** Crumb */
        Crumb: {
            /** Scope */
            scope: string;
            /** Name */
            name: string;
        };
        /** DependencyEdge */
        DependencyEdge: {
            /**
             * Node
             * @description the other end, named as seen from the component's parent level
             */
            node: string;
            /** Refs */
            refs: number;
            /** Calls */
            calls: number;
            /** Uses */
            uses: number;
            /** Declared */
            declared: boolean;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @description not_found, validation_failed or another machine-readable code
             */
            code: string;
            /** Message */
            message: string;
            /**
             * Details
             * @default []
             */
            details: unknown[];
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** FactsStatus */
        FactsStatus: {
            /** Files */
            files: number;
            /** Symbols */
            symbols: number;
            /** Refs */
            refs: number;
            /** Relations */
            relations: number;
            /** Facts Version */
            facts_version: string | null;
            /**
             * Platform
             * @description OS the facts were indexed on: code under #ifdef for other OSes is not in them
             */
            platform: string | null;
            /** Loaded At */
            loaded_at: string | null;
        };
        /** InterfaceSymbol */
        InterfaceSymbol: {
            /** Id */
            id: string;
            /**
             * Present
             * @description false when the anchor is not in the facts
             */
            present: boolean;
            /** Name */
            name: string | null;
            /** Kind */
            kind: string | null;
            /** Signature */
            signature: string | null;
            /** Path */
            path: string | null;
        };
        /** Issue */
        Issue: {
            /**
             * Code
             * @enum {string}
             */
            code: "invalid_model" | "broken_anchor" | "ambiguous_membership" | "empty" | "stale" | "missing_dependency" | "undeclared_dependency" | "cycle";
            /** Component */
            component: string | null;
            /** Target */
            target: string | null;
            /** Members */
            members: string[];
            /** Scope */
            scope: string | null;
            /** Symbols */
            symbols: string[];
            /** Count */
            count: number;
            /** Message */
            message: string;
            /**
             * Text
             * @description one line for people
             */
            text: string;
        };
        /** LayoutBody */
        LayoutBody: {
            /**
             * Positions
             * @description node ID -> pinned position; an empty object unpins the level
             */
            positions: {
                [key: string]: components["schemas"]["Position"];
            };
        };
        /** LayoutResult */
        LayoutResult: {
            /** Scope */
            scope: string;
            /** Positions */
            positions: {
                [key: string]: components["schemas"]["Position"];
            };
        };
        /** Location */
        Location: {
            /** Path */
            path: string;
            /**
             * Line
             * @description 1-based line of the name
             */
            line: number;
            /**
             * Column
             * @description 1-based column of the name, in UTF-8 bytes
             */
            column: number;
            /**
             * End Line
             * @description 1-based last line of the whole declaration
             */
            end_line: number;
        };
        /** PathList */
        PathList: {
            /** Paths */
            paths: string[][];
        };
        /** Place */
        Place: {
            /** Scope */
            scope: string;
            /** Node */
            node: string;
        };
        /** Position */
        Position: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** RefList */
        RefList: {
            /** Items */
            items: components["schemas"]["RefSample"][];
            /** More */
            more: boolean;
        };
        /** RefSample */
        RefSample: {
            /** Symbol */
            symbol: string;
            /** Container */
            container: string | null;
            /** Path */
            path: string;
            /** Line */
            line: number;
            /** Column */
            column: number;
            /** Roles */
            roles: string[];
        };
        /** Status */
        Status: {
            /**
             * Version
             * @description carma package version
             */
            version: string;
            contracts: components["schemas"]["Contracts"];
            /** Project Root */
            project_root: string;
            /** Project Name */
            project_name: string;
            facts: components["schemas"]["FactsStatus"];
            /** Components */
            components: number;
            /** Invalid Files */
            invalid_files: string[];
            /** Issues */
            issues: number;
            /** Highlight */
            highlight: boolean;
        };
        /** SymbolBrief */
        SymbolBrief: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Signature */
            signature: string | null;
            /**
             * Component
             * @description component ID, _unassigned or _external; null for namespaces
             */
            component: string | null;
            /**
             * Path
             * @description the file that decides membership
             */
            path: string | null;
            /** Line */
            line: number | null;
            /** External */
            external: boolean;
        };
        /** SymbolCard */
        SymbolCard: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Signature */
            signature: string | null;
            /** Doc */
            doc: string | null;
            /** Access */
            access: string | null;
            /** Parent */
            parent: string | null;
            /** External */
            external: boolean;
            /** Component */
            component: string | null;
            /** Defs */
            defs: components["schemas"]["Location"][];
            /** Decls */
            decls: components["schemas"]["Location"][];
            /** @description the level and node that draw this symbol on the map */
            place: components["schemas"]["Place"] | null;
            /**
             * Editor Uri
             * @description editor_uri from config.yaml filled with the definition
             */
            editor_uri: string | null;
        };
        /** SymbolList */
        SymbolList: {
            /** Items */
            items: components["schemas"]["SymbolBrief"][];
            /**
             * More
             * @description true when the list was cut at limit
             */
            more: boolean;
        };
        /** TreeNode */
        TreeNode: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "system" | "subsystem" | "component";
            /**
             * Lifecycle
             * @enum {string}
             */
            lifecycle: "current" | "planned" | "deprecated";
            /** Symbols */
            symbols: number;
            /** Own Symbols */
            own_symbols: number;
            /** Issues */
            issues: ("invalid_model" | "broken_anchor" | "ambiguous_membership" | "empty" | "stale" | "missing_dependency" | "undeclared_dependency" | "cycle")[];
            /** Children */
            children: components["schemas"]["TreeNode"][];
        };
        /** View */
        View: {
            /** Scope */
            scope: string;
            /**
             * Level
             * @enum {string}
             */
            level: "components" | "symbols";
            /**
             * Component
             * @description 'root' or the component whose children or symbols the level shows
             */
            component: string;
            /**
             * Trail
             * @description breadcrumbs from the root down to this level
             */
            trail: components["schemas"]["Crumb"][];
            /** Nodes */
            nodes: components["schemas"]["ViewNode"][];
            /** Edges */
            edges: components["schemas"]["ViewEdge"][];
            /**
             * Boundary
             * @description neighbors outside the level that edges lead to, drawn pale
             */
            boundary: components["schemas"]["ViewNode"][];
            /**
             * Grouped By
             * @description set when the level had more than max_nodes nodes
             */
            grouped_by: ("file" | "folder") | null;
        };
        /** ViewEdge */
        ViewEdge: {
            /** Src */
            src: string;
            /** Dst */
            dst: string;
            /** Refs */
            refs: number;
            /** Calls */
            calls: number;
            /** Uses */
            uses: number;
            /**
             * Declared
             * @description the target is in requires of the source or of one of its ancestors
             */
            declared: boolean;
            /** Issues */
            issues: ("invalid_model" | "broken_anchor" | "ambiguous_membership" | "empty" | "stale" | "missing_dependency" | "undeclared_dependency" | "cycle")[];
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
        };
        /** ViewMember */
        ViewMember: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @description field, variable, method, constructor, destructor or function
             */
            kind: string;
            /** Signature */
            signature: string | null;
            /** Access */
            access: string | null;
        };
        /** ViewNode */
        ViewNode: {
            /**
             * Id
             * @description component ID, '<id>._self', '_unassigned', symbol ID, 'file:<path>' or 'folder:<path>'
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "component" | "self" | "unassigned" | "symbol" | "file" | "folder";
            /**
             * Kind
             * @description system, subsystem or component; for symbol nodes the symbol kind
             */
            kind: string | null;
            /** Lifecycle */
            lifecycle: ("current" | "planned" | "deprecated") | null;
            /** Intent Short */
            intent_short: string;
            /**
             * Symbols
             * @description symbols inside the node, descendants included
             */
            symbols: number;
            /**
             * Children
             * @description child components
             */
            children: number;
            /**
             * File
             * @description symbol nodes and file groups: the file the node belongs to
             */
            file: string | null;
            /** Issues */
            issues: ("invalid_model" | "broken_anchor" | "ambiguous_membership" | "empty" | "stale" | "missing_dependency" | "undeclared_dependency" | "cycle")[];
            /** @description position pinned in layout.json, else null */
            pos: components["schemas"]["Position"] | null;
            /**
             * Metrics
             * @description runtime metrics; empty in v0
             */
            metrics: {
                [key: string]: number;
            };
            /**
             * Members
             * @description direct fields and methods of a class, struct or union; empty otherwise
             */
            members: components["schemas"]["ViewMember"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status_api_v0_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    view_api_v0_view_get: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    components_api_v0_components_get: {
        parameters: {
            query?: {
                parent?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentTree"];
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    component_api_v0_components__component_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                component_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentCard"];
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_api_v0_symbols_search_get: {
        parameters: {
            query: {
                q: string;
                /** @description repeat for several kinds */
                kind?: string[] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolList"];
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    symbol_api_v0_symbols_get: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolCard"];
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    callers_api_v0_symbols_callers_get: {
        parameters: {
            query: {
                id: string;
                depth?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallList"];
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    callees_api_v0_symbols_callees_get: {
        parameters: {
            query: {
                id: string;
                depth?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallList"];
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    paths_api_v0_paths_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                max_depth?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathList"];
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    samples_api_v0_edges_samples_get: {
        parameters: {
            query: {
                src: string;
                dst: string;
                scope?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefList"];
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    layout_api_v0_layout__scope__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scope: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutResult"];
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    events_api_v0_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description an event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description unknown ID or scope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
